### ISSUE TITLE
node-sass version not compatible with node 16

### ISSUE THREAD

**Issue by bruceharrison1984** [nibdo/calend#14]
Trying to bring this into a nodeJS 16 project results in node-sass failing to build during install.

[Node-sass supports nodeJS 16 starting with v6.0.0.](https://github.com/sass/node-sass/releases/tag/v6.0.0)

**Comment by bruceharrison1984** [comment]
As a side note, I'm glad you picked up the torch for a React Calendar component. I was days away from starting on something very similar to this since current calendar components all have big deficits in one area or another.

**Comment by nibdo** [comment]
Hello, thank you, hope it could be useful for you. 

I see the problem, for now I will try to compile .scss files directly to .css in build process and ditch node-sass as main dependency and leave it for now only for dev. Upgrading should solve this, but I think this would bring similar incompatibility for users with node 14 or less. I was already thinking about using something like styled components instead of scss, but not decided yet.

About your other problem here https://github.com/nibdo/calend/issues/15 I will check what I could do about it.

**Comment by bruceharrison1984** [comment]
Thanks for the reply! Looking forward to see where this goes

**Comment by bruceharrison1984** [comment]
you fixed it!

**Comment by nibdo** [comment]
:) Thanks again for discovering those issues. Next.js should be fine now too, tried it on one project.
